INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l14d1','mfv1_l14','Mei','你有什么？','Nǐ yǒu shénme?','What do you have?','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l14d2','mfv1_l14','Kai','我有一支铅笔。','Wǒ yǒu yì zhī qiānbǐ.','I have a pencil.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l14a1','mfv1_l14','listen_tap','Listen and choose book.','书',jsonb_build_array('铅笔','桌子'),'书 (shū) means book.',1,'f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l14a2','mfv1_l14','mcq','Choose the best expression for this lesson.','本',jsonb_build_array('桌子','椅子'),'本 is the classifier used here for a book.',1,'f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l14q1','mfv1_l14','What does 书 mean?','mcq','book',jsonb_build_array('pencil','desk / table'),'书 means book.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l14q2','mfv1_l14','Which Mandarin expression means pencil?','mcq','铅笔',jsonb_build_array('桌子','椅子'),'铅笔 (qiānbǐ) means pencil.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l14q3','mfv1_l14','Choose the Pinyin for 桌子.','listen_tap','zhuōzi',jsonb_build_array('shū','yǐzi'),'桌子 is pronounced zhuōzi.','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l14q4','mfv1_l14','Complete: 一____书','fill_blank','本',jsonb_build_array('桌子','椅子'),'本 is the classifier used here for a book.','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l14q5','mfv1_l14','Which sentence best shows: name and count classroom objects?','mcq','这是一本书。',jsonb_build_array('桌子','椅子'),'这是一本书。 means This is a book..','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
