INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l15d1','mfv1_l15','Kai','你的书包是什么颜色？','Nǐ de shūbāo shì shénme yánsè?','What colour is your school bag?','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l15d2','mfv1_l15','Mei','是红色的。','Shì hóngsè de.','It is red.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l15a1','mfv1_l15','listen_tap','Listen and choose red.','红色',jsonb_build_array('蓝色','黄色'),'红色 (hóngsè) means red.',1,'f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l15a2','mfv1_l15','match','Match the Mandarin to its meaning.','蓝色 = blue',jsonb_build_array('黄色 = blue','绿色 = blue'),'的 completes this colour-description pattern.',1,'f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l15q1','mfv1_l15','What does 红色 mean?','mcq','red',jsonb_build_array('blue','yellow'),'红色 means red.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l15q2','mfv1_l15','Which Mandarin expression means blue?','mcq','蓝色',jsonb_build_array('黄色','绿色'),'蓝色 (lánsè) means blue.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l15q3','mfv1_l15','Choose the Pinyin for 黄色.','listen_tap','huángsè',jsonb_build_array('hóngsè','lǜsè'),'黄色 is pronounced huángsè.','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l15q4','mfv1_l15','Complete: 书包是蓝色____。','fill_blank','的',jsonb_build_array('黄色','绿色'),'的 completes this colour-description pattern.','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l15q5','mfv1_l15','Which sentence best shows: identify and name colours?','mcq','我的书包是蓝色的。',jsonb_build_array('黄色','绿色'),'我的书包是蓝色的。 means My school bag is blue..','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
