INSERT INTO course_lessons (id, course_id, module_sequence, sequence, title, objective, explanation, status, xp_reward) VALUES ('mfv1_l15', 'mandarin_foundation_v1', 2, 15, 'Colours', 'Recognise and name basic colours.', 'Colour words can come before 色, which means "colour." 红色 is red and 蓝色 is blue. When naming a colour, you can simply say the colour word.', 'ready', 100) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, objective=EXCLUDED.objective, explanation=EXCLUDED.explanation, status=EXCLUDED.status, xp_reward=EXCLUDED.xp_reward;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l15v1','mfv1_l15','红色','hóngsè','red','colour','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l15v2','mfv1_l15','蓝色','lánsè','blue','colour','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l15v3','mfv1_l15','黄色','huángsè','yellow','colour','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l15v4','mfv1_l15','绿色','lǜsè','green','colour','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l15v5','mfv1_l15','白色','báisè','white','colour','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l15e1','mfv1_l15','我的书包是蓝色的。','Wǒ de shūbāo shì lánsè de.','My school bag is blue.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l15e2','mfv1_l15','我喜欢绿色。','Wǒ xǐhuan lǜsè.','I like green.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO grammar_patterns (id,lesson_id,pattern,explanation,chinese,pinyin,english,source_id,review_status) VALUES ('l15g1','mfv1_l15','noun + 是 + colour + 的','Use 是…的 to identify the colour of something.','书包是蓝色的。','Shūbāo shì lánsè de.','The school bag is blue.','f1000000-0000-4000-8000-000000000001','pending') ON CONFLICT (id) DO UPDATE SET pattern=EXCLUDED.pattern,explanation=EXCLUDED.explanation,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
