INSERT INTO course_lessons (id, course_id, module_sequence, sequence, title, objective, explanation, status, xp_reward) VALUES ('mfv1_l16', 'mandarin_foundation_v1', 2, 16, 'What Is This?', 'Ask and answer what an object is.', '这是什么？ asks "What is this?" Answer with 这是 plus the object. 什么 stays in the place where the missing information belongs.', 'ready', 100) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, objective=EXCLUDED.objective, explanation=EXCLUDED.explanation, status=EXCLUDED.status, xp_reward=EXCLUDED.xp_reward;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l16v1','mfv1_l16','什么','shénme','what','question word','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l16v2','mfv1_l16','这','zhè','this','pronoun','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l16v3','mfv1_l16','那','nà','that','pronoun','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l16v4','mfv1_l16','东西','dōngxi','thing','noun','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l16v5','mfv1_l16','书包','shūbāo','school bag','noun','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l16e1','mfv1_l16','这是什么？','Zhè shì shénme?','What is this?','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l16e2','mfv1_l16','这是书包。','Zhè shì shūbāo.','This is a school bag.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO grammar_patterns (id,lesson_id,pattern,explanation,chinese,pinyin,english,source_id,review_status) VALUES ('l16g1','mfv1_l16','这 + 是 + 什么？','Replace the unknown object with 什么.','这是什么？','Zhè shì shénme?','What is this?','f1000000-0000-4000-8000-000000000001','pending') ON CONFLICT (id) DO UPDATE SET pattern=EXCLUDED.pattern,explanation=EXCLUDED.explanation,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
