INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l16d1','mfv1_l16','Mei','这是什么？','Zhè shì shénme?','What is this?','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l16d2','mfv1_l16','Kai','这是书包。','Zhè shì shūbāo.','This is a school bag.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l16a1','mfv1_l16','listen_tap','Listen and choose what.','什么',jsonb_build_array('这','那'),'什么 (shénme) means what.',1,'f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l16a2','mfv1_l16','fill_blank','Complete the key expression: 这是____？','什么',jsonb_build_array('那','东西'),'什么 fills the unknown-object slot.',1,'f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l16q1','mfv1_l16','What does 什么 mean?','mcq','what',jsonb_build_array('this','that'),'什么 means what.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l16q2','mfv1_l16','Which Mandarin expression means this?','mcq','这',jsonb_build_array('那','东西'),'这 (zhè) means this.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l16q3','mfv1_l16','Choose the Pinyin for 那.','listen_tap','nà',jsonb_build_array('shénme','dōngxi'),'那 is pronounced nà.','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l16q4','mfv1_l16','Complete: 这是____？','fill_blank','什么',jsonb_build_array('那','东西'),'什么 fills the unknown-object slot.','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l16q5','mfv1_l16','Which sentence best shows: ask and identify an object?','mcq','这是什么？',jsonb_build_array('那','东西'),'这是什么？ means What is this?.','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
