INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l18d1','mfv1_l18','Mei','你喜欢什么？','Nǐ xǐhuan shénme?','What do you like?','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l18d2','mfv1_l18','Kai','我喜欢音乐。','Wǒ xǐhuan yīnyuè.','I like music.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l18a1','mfv1_l18','listen_tap','Listen and choose to like.','喜欢',jsonb_build_array('我','苹果'),'喜欢 (xǐhuan) means to like.',1,'f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l18a2','mfv1_l18','match','Match the Mandarin to its meaning.','我 = I / me',jsonb_build_array('苹果 = I / me','音乐 = I / me'),'喜欢 goes between the person and liked thing.',1,'f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l18q1','mfv1_l18','What does 喜欢 mean?','mcq','to like',jsonb_build_array('I / me','apple'),'喜欢 means to like.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l18q2','mfv1_l18','Which Mandarin expression means I / me?','mcq','我',jsonb_build_array('苹果','音乐'),'我 (wǒ) means I / me.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l18q3','mfv1_l18','Choose the Pinyin for 苹果.','listen_tap','píngguǒ',jsonb_build_array('xǐhuan','yīnyuè'),'苹果 is pronounced píngguǒ.','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l18q4','mfv1_l18','Complete: 我____苹果。','fill_blank','喜欢',jsonb_build_array('苹果','音乐'),'喜欢 goes between the person and liked thing.','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l18q5','mfv1_l18','Which sentence best shows: say what you like?','mcq','我喜欢苹果。',jsonb_build_array('苹果','音乐'),'我喜欢苹果。 means I like apples..','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
