INSERT INTO course_lessons (id, course_id, module_sequence, sequence, title, objective, explanation, status, xp_reward) VALUES ('mfv1_l18', 'mandarin_foundation_v1', 2, 18, 'I Like…', 'Say what you like.', '喜欢 means "to like." Put the person first, then 喜欢, then the liked thing or action. Mandarin does not change 喜欢 for different people.', 'ready', 100) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, objective=EXCLUDED.objective, explanation=EXCLUDED.explanation, status=EXCLUDED.status, xp_reward=EXCLUDED.xp_reward;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l18v1','mfv1_l18','喜欢','xǐhuan','to like','verb','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l18v2','mfv1_l18','我','wǒ','I / me','pronoun','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l18v3','mfv1_l18','苹果','píngguǒ','apple','noun','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l18v4','mfv1_l18','音乐','yīnyuè','music','noun','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l18v5','mfv1_l18','看书','kàn shū','read books','verb phrase','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l18e1','mfv1_l18','我喜欢苹果。','Wǒ xǐhuan píngguǒ.','I like apples.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l18e2','mfv1_l18','我喜欢看书。','Wǒ xǐhuan kàn shū.','I like reading books.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO grammar_patterns (id,lesson_id,pattern,explanation,chinese,pinyin,english,source_id,review_status) VALUES ('l18g1','mfv1_l18','person + 喜欢 + thing/action','Put what is liked after 喜欢.','我喜欢音乐。','Wǒ xǐhuan yīnyuè.','I like music.','f1000000-0000-4000-8000-000000000001','pending') ON CONFLICT (id) DO UPDATE SET pattern=EXCLUDED.pattern,explanation=EXCLUDED.explanation,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
