INSERT INTO course_lessons (id, course_id, module_sequence, sequence, title, objective, explanation, status, xp_reward) VALUES ('mfv1_l19', 'mandarin_foundation_v1', 2, 19, 'I Don''t Like…', 'Say what you do not like.', 'Put 不 before 喜欢 to make 不喜欢, "do not like." This gives a calm preference; use a kind voice when talking about someone else''s food or choice.', 'ready', 100) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, objective=EXCLUDED.objective, explanation=EXCLUDED.explanation, status=EXCLUDED.status, xp_reward=EXCLUDED.xp_reward;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l19v1','mfv1_l19','不喜欢','bù xǐhuan','do not like','verb phrase','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l19v2','mfv1_l19','不','bù','not','adverb','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l19v3','mfv1_l19','喜欢','xǐhuan','to like','verb','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l19v4','mfv1_l19','牛奶','niúnǎi','milk','noun','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO vocab_items (id, lesson_id, simplified_chinese, pinyin, english_meaning, part_of_speech, source_id, review_status, sequence) VALUES ('l19v5','mfv1_l19','面条','miàntiáo','noodles','noun','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET simplified_chinese=EXCLUDED.simplified_chinese,pinyin=EXCLUDED.pinyin,english_meaning=EXCLUDED.english_meaning,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l19e1','mfv1_l19','我不喜欢牛奶。','Wǒ bù xǐhuan niúnǎi.','I do not like milk.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO examples (id,lesson_id,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l19e2','mfv1_l19','他不喜欢面条。','Tā bù xǐhuan miàntiáo.','He does not like noodles.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO grammar_patterns (id,lesson_id,pattern,explanation,chinese,pinyin,english,source_id,review_status) VALUES ('l19g1','mfv1_l19','person + 不 + verb','Place 不 directly before the verb to make it negative.','我不喜欢牛奶。','Wǒ bù xǐhuan niúnǎi.','I do not like milk.','f1000000-0000-4000-8000-000000000001','pending') ON CONFLICT (id) DO UPDATE SET pattern=EXCLUDED.pattern,explanation=EXCLUDED.explanation,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
