INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l19d1','mfv1_l19','Kai','你喜欢牛奶吗？','Nǐ xǐhuan niúnǎi ma?','Do you like milk?','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO dialogues (id,lesson_id,speaker,chinese,pinyin,english,source_id,review_status,sequence) VALUES ('l19d2','mfv1_l19','Mei','我不喜欢牛奶。','Wǒ bù xǐhuan niúnǎi.','I do not like milk.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET speaker=EXCLUDED.speaker,chinese=EXCLUDED.chinese,pinyin=EXCLUDED.pinyin,english=EXCLUDED.english,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l19a1','mfv1_l19','listen_tap','Listen and choose do not like.','不喜欢',jsonb_build_array('不','喜欢'),'不喜欢 (bù xǐhuan) means do not like.',1,'f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO activities (id,lesson_id,type,prompt,answer,distractors,explanation,difficulty,source_id,review_status,sequence) VALUES ('l19a2','mfv1_l19','fill_blank','Complete the key expression: 我____喜欢牛奶。','不',jsonb_build_array('喜欢','牛奶'),'不 before 喜欢 makes the sentence negative.',1,'f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET prompt=EXCLUDED.prompt,answer=EXCLUDED.answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l19q1','mfv1_l19','What does 不喜欢 mean?','mcq','do not like',jsonb_build_array('not','to like'),'不喜欢 means do not like.','f1000000-0000-4000-8000-000000000001','pending',1) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l19q2','mfv1_l19','Which Mandarin expression means not?','mcq','不',jsonb_build_array('喜欢','牛奶'),'不 (bù) means not.','f1000000-0000-4000-8000-000000000001','pending',2) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l19q3','mfv1_l19','Choose the Pinyin for 喜欢.','listen_tap','xǐhuan',jsonb_build_array('bù xǐhuan','niúnǎi'),'喜欢 is pronounced xǐhuan.','f1000000-0000-4000-8000-000000000001','pending',3) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l19q4','mfv1_l19','Complete: 我____喜欢牛奶。','fill_blank','不',jsonb_build_array('喜欢','牛奶'),'不 before 喜欢 makes the sentence negative.','f1000000-0000-4000-8000-000000000001','pending',4) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
INSERT INTO assessment_items (id,lesson_id,question,type,correct_answer,distractors,explanation,source_id,review_status,sequence) VALUES ('l19q5','mfv1_l19','Which sentence best shows: state a dislike politely?','mcq','我不喜欢牛奶。',jsonb_build_array('喜欢','牛奶'),'我不喜欢牛奶。 means I do not like milk..','f1000000-0000-4000-8000-000000000001','pending',5) ON CONFLICT (id) DO UPDATE SET question=EXCLUDED.question,correct_answer=EXCLUDED.correct_answer,distractors=EXCLUDED.distractors,explanation=EXCLUDED.explanation,review_status=EXCLUDED.review_status;
